import type { Metadata } from 'next';
import Link from 'next/link';

import { GuideArticleView } from '@/components/guide-article-view';
import { energyGuides } from '@/content/guides';
import { createPageMetadata } from '@/lib/metadata';

import styles from '@/components/guide-article-view.module.css';

const guide = energyGuides['estimated-vs-actual-meter-reading']!;

export const metadata: Metadata = createPageMetadata({
  title: guide.title,
  description: guide.description,
  path: guide.href,
});

export default function GuideEstimatedVsActualMeterPage() {
  return (
    <GuideArticleView guide={guide}>
      <section className={styles.section}>
        <h2>Direct Answer: Estimated vs. Actual Meter Reading</h2>
        <p>
          An <strong>Actual Meter Reading</strong> measures exact cumulative kilowatt-hours (kWh)
          recorded directly from a physical meter dial or digital smart meter on your scheduled
          billing date.
        </p>
        <p>
          An <strong>Estimated Meter Reading</strong> is a calculated usage placeholder generated by
          the utility when physical access is blocked or wireless smart meter telemetry fails.
          Estimated readings do not necessarily indicate billing errors, but they defer actual meter
          reconciliation to subsequent billing cycles.
        </p>
      </section>

      <section className={styles.section}>
        <h2>Meter Estimation Algorithms, Smart Meters & True-Up Spikes</h2>
        <p>
          Understanding estimated meter statements helps explain sudden electric bill adjustments:
        </p>
        <ul>
          <li>
            <strong>Why Estimates Occur:</strong> Physical meter access barriers (locked gates,
            overgrown foliage, loose dogs, severe weather) or cellular smart meter transmission
            outages force utility estimation algorithms to generate statements.
          </li>
          <li>
            <strong>Estimation Methodology:</strong> Utilities estimate usage based on your
            historical consumption during the same calendar month in prior years, adjusted for
            current weather heating or cooling degree days.
          </li>
          <li>
            <strong>The True-Up Adjustment Spike:</strong> If a utility under-estimates usage for 2
            to 3 consecutive months, the next actual meter reading captures all accumulated unbilled
            kWh in a single statement, triggering a sudden catch-up bill spike.
          </li>
        </ul>
        <div className={styles.formulaBox}>
          Reconciled Actual Usage (kWh) = Current Actual Meter Reading − Previous Billed Reading
        </div>
      </section>

      <section className={styles.section}>
        <h2>Sample True-Up Reconciliation Sequence</h2>
        <div className={styles.tableWrapper}>
          <table
            aria-label="3-month billing sequence showing estimated readings followed by an actual true-up reading"
            className={styles.dataTable}
          >
            <caption>Sample 3-Month Meter Sequence: Estimated Bills vs. Actual True-Up</caption>
            <thead>
              <tr>
                <th scope="col">Month</th>
                <th scope="col">Reading Type</th>
                <th scope="col">Cumulative Meter Dial</th>
                <th scope="col">Billed Monthly kWh</th>
                <th scope="col">Billed Statement Amount</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Month 1</td>
                <td>Estimated Reading</td>
                <td>45,000 kWh (Est)</td>
                <td>800 kWh</td>
                <td>$160.00</td>
              </tr>
              <tr>
                <td>Month 2</td>
                <td>Estimated Reading</td>
                <td>45,800 kWh (Est)</td>
                <td>800 kWh</td>
                <td>$160.00</td>
              </tr>
              <tr>
                <td>Month 3</td>
                <td>Actual Meter Reading</td>
                <td>47,800 kWh (Actual)</td>
                <td>1,200 kWh (True-Up)</td>
                <td>$240.00 (Catch-Up Spike)</td>
              </tr>
            </tbody>
          </table>
        </div>
        <p className={styles.tableFootnote}>
          * Note: Statement indicator codes ("EST" vs "ACT") appear on utility bills next to the
          meter reading table. Figures represent an illustrative calculation assumption.
        </p>
      </section>

      <section className={styles.section}>
        <h2>Assumptions & When to Contact Your Utility</h2>
        <p>
          If your bill displays an "EST" indicator tag for multiple consecutive billing cycles,
          inspect your physical meter display to take a manual reading, ensure clear meter access,
          and submit a customer reading directly to your utility customer service portal.
        </p>
        <p>
          Analyze your meter statement with our{' '}
          <Link href="/electricity-bill-analyzer">Electricity Bill Analyzer</Link> or learn more
          about billing cycles in our{' '}
          <Link href="/guides/how-billing-cycle-length-affects-electricity-bills">
            Billing Cycle Length Guide
          </Link>{' '}
          or high bill diagnostics:{' '}
          <Link href="/guides/why-is-my-electric-bill-so-high">
            Why Is My Electric Bill So High?
          </Link>
          .
        </p>
      </section>
    </GuideArticleView>
  );
}
