import type { Metadata } from 'next';
import Link from 'next/link';

import { GuideArticleView } from '@/components/guide-article-view';
import { energyGuides } from '@/content/guides';
import { createPageMetadata } from '@/lib/metadata';

import styles from '@/components/guide-article-view.module.css';

const guide = energyGuides['how-net-metering-affects-your-electric-bill']!;

export const metadata: Metadata = createPageMetadata({
  title: guide.title,
  description: guide.description,
  path: guide.href,
});

export default function GuideNetMeteringPage() {
  return (
    <GuideArticleView guide={guide}>
      <section className={styles.section}>
        <h2>Direct Answer: How Net Metering Affects Your Electric Bill</h2>
        <p>
          <strong>Net Energy Metering (NEM)</strong> is a utility billing mechanism that credits
          rooftop solar owners for surplus electricity generated by their solar panels and exported
          to the electric grid.
        </p>
        <p>
          Your monthly bill calculates <strong>Net Grid Energy</strong> (Imported kWh − Exported
          kWh). However, net metering compensation rules vary significantly by state—ranging from
          1:1 full retail rate credits to reduced avoided-cost export rates (such as California's
          Net Billing Tariff, commonly known as NEM 3.0).
        </p>
      </section>

      <section className={styles.section}>
        <h2>Bi-Directional Metering, Solar Credits & True-Ups</h2>
        <p>Solar net metering statements incorporate specific mechanical and policy rules:</p>
        <ul>
          <li>
            <strong>Bi-Directional Smart Metering:</strong> A specialized utility meter records
            electricity imported from the grid when solar panels are not producing (e.g., at night)
            and electricity exported to the grid during sunny afternoon peak production.
          </li>
          <li>
            <strong>Compensation Structures:</strong> Under classic 1:1 net metering laws, exported
            kWh receives full retail credit value. California-specific example: earlier California
            tariffs (NEM 1.0 and 2.0) provided 1:1 retail credits, whereas California's current Net
            Billing Tariff (NEM 3.0) credits surplus generation at variable wholesale avoided-cost
            rates.
          </li>
          <li>
            <strong>Monthly Carryover & Annual True-Up:</strong> Excess monthly export credits carry
            forward to offset future bills. At the end of a 12-month billing cycle, an annual
            true-up reconciles remaining solar credits.
          </li>
          <li>
            <strong>Minimum Bills & Fixed Fees:</strong> Net metering does not eliminate all utility
            expenses; solar customers remain responsible for fixed monthly customer connection fees
            and mandatory minimum bills.
          </li>
        </ul>
        <div className={styles.formulaBox}>
          Net Grid Consumption (kWh) = Total Grid Imported kWh − Total Grid Exported kWh
        </div>
      </section>

      <section className={styles.section}>
        <h2>Net Metering Policy Comparison: Full Retail vs. Net Billing</h2>
        <div className={styles.tableWrapper}>
          <table
            aria-label="Net metering compensation comparison across policy structures"
            className={styles.dataTable}
          >
            <caption>
              Solar Net Metering Billing Structures (800 kWh Import / 600 kWh Export)
            </caption>
            <thead>
              <tr>
                <th scope="col">Net Metering Policy</th>
                <th scope="col">Export Credit Rate</th>
                <th scope="col">Grid Import Cost (20¢)</th>
                <th scope="col">Export Credit Value</th>
                <th scope="col">Monthly Energy Charge</th>
                <th scope="col">Minimum Fixed Charge</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Classic 1:1 Retail Net Metering (Legacy Tariffs)</td>
                <td>100% Retail Rate (20.0 ¢/kWh)</td>
                <td>$160.00</td>
                <td>-$120.00</td>
                <td>$40.00</td>
                <td>+$12.00 Fixed Fee</td>
              </tr>
              <tr>
                <td>Avoided-Cost Net Billing (California NEM 3.0)</td>
                <td>Avoided Cost (~6.0 ¢/kWh)</td>
                <td>$160.00</td>
                <td>-$36.00</td>
                <td>$124.00</td>
                <td>+$12.00 Fixed Fee</td>
              </tr>
              <tr>
                <td>Buy-All / Sell-All Tariff</td>
                <td>Wholesale Rate (~4.0 ¢/kWh)</td>
                <td>$160.00</td>
                <td>-$24.00</td>
                <td>$136.00</td>
                <td>+$12.00 Fixed Fee</td>
              </tr>
            </tbody>
          </table>
        </div>
        <p className={styles.tableFootnote}>
          * Note: Solar export credit rates, true-up schedules, and fixed grid fees vary by state
          public utility commission regulations and utility tariff. Figures represent an
          illustrative calculation assumption.
        </p>
      </section>

      <section className={styles.section}>
        <h2>Assumptions & Jurisdictional Differences</h2>
        <p>
          Rooftop solar panels do not automatically eliminate your electric bill. Always check your
          specific electric utility solar interconnection tariff to verify export credit rates and
          fixed customer charges.
        </p>
        <p>
          Analyze your net meter statement with our{' '}
          <Link href="/electricity-bill-analyzer">Electricity Bill Analyzer</Link> or learn more
          about TOU solar interaction in our{' '}
          <Link href="/guides/what-is-a-time-of-use-electricity-rate">
            Time-of-Use Electricity Rate Guide
          </Link>{' '}
          or state rates on our{' '}
          <Link href="/electricity-rates">U.S. Electricity Rates Directory</Link>.
        </p>
      </section>
    </GuideArticleView>
  );
}
